---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  annotations: {}
  name: "mysql-pv-claim"
  labels:
    app: "wordpress"
    app.kubernetes.io/name: "wordpress"
spec:
  accessModes:
  - "ReadWriteOnce"
  storageClassName: "nirmata-hostpath"
  resources:
    limits: {}
    requests:
      storage: "20Gi"
